### ISSUE TITLE
Pilot Markus: Step 4 and 5 Normal distribution

### ISSUE THREAD

**Issue by rbritto82** [DeepikaBadampudi/qmethod#13]
it is hard to keep everything in your head when you are supposed to find the least/most. It felt like I agreed with basically everything so I had to look over everything to find something to disagree with.
Realised that I had something in -3 that I did not necessarly want there.

**Comment by rbritto82** [comment]
@munterkalmsteiner and @DeepikaBadampudi, I wonder whether we can use the "least like I think" approach to step 3 as well. As mentioned by Markus, at times you don't necessarily disagree. Rather, you don't think something is that important.

**Comment by DeepikaBadampudi** [comment]
Yes, that would make sense. However, the previous respondents did disagree with some statements. With "least like I think", we would not know if they disagree or they did not think about it because they never experienced or gave any thought before. We would like to differentiate the two reasons. In Step 3 we are not forcing respondents to disagree as we had in Step 4. It should still work if they do not have anything in the disagree pile.

**Comment by munterkalmsteiner** [comment]
Same issue as #6

**Comment by munterkalmsteiner** [comment]
> @munterkalmsteiner and @DeepikaBadampudi, I wonder whether we can use the "least like I think" approach to step 3 as well. As mentioned by Markus, at times you don't necessarily disagree. Rather, you don't think something is that important.

And that is actually what we want to capture as we have formulated the statements accordingly: It is important to.... 
Respondents should be able to say whether they agree/disagree that something is important.
