### ISSUE TITLE
Pilot: Anton - Normal distribution of statement ratings

### ISSUE THREAD

**Issue by munterkalmsteiner** [DeepikaBadampudi/qmethod#6]
The step with ranking into buckets is probably really good for the collection of data but can be a bit restricting since we already have rough buckets (Accept, Neutral, Disagree). Let’s say I disagree strongly with everything, then I MUST add some of them to agreed strongly. Perhaps not something to do anything about but be aware of.

**Comment by munterkalmsteiner** [comment]
Look into whether for the analysis it is necessary that ratings of statements are distributed by a particular distribution.

**Comment by DeepikaBadampudi** [comment]
**Normal distribution is not required** - The statements need not be distributed in a normal distribution. There are two types of sorting: 
- Forced qsorting - statements are distributed in a normal distribution. 
- UnForced qsorting - statements are distributed in a free-form distribution. 

Look at - Webler, T., S. Danielson, et al. (2009). Using Q method to reveal social perspectives in environmental research. Greenfield MA, Social and Environmental Research Institute. [link to paper](seri-us.org/sites/default/files/Qprimer.pdf) 

**A normal distribution is preferred** - A normal distribution is encouraged as it helps to sort the statements in a thoughtful way and helps to reveal the preferences. Some text from the Webler 2009 - "If participants are encouraged to assign statements any ranking, then some will quickly divide the pile into two extremes and claim to be “finished.” Revealing preferences sometimes takes more work than this."

**Balanced statements -** We should have balanced statements such that half of the statements will be sorted on the right half and the other on the left half. However, it is not always possible. 

**Possible solutions** - Since the normal distribution is preferred, one solution could be to change the instructions for Step 4. Instead of asking for most agree to disagree, we can ask this - "Please sort these statements from those which are most like, to those which are least like your point of view".  The tail values will be "least like how I think" and "most like how I think". [Example here](https://steps-centre.org/pathways-methods-vignettes/methods-vignettes-q-method/).

**Pilot evaluation** - I looked at the 3 pilot responses. There are fewer statements in the disagree pile (as we expected). However, in the rating, the neutral statements are pushed to the minus ratings and not the agreed ones (I looked at one respondent). Which is good. We do not want many statements in the neutral category. It might be a problem if a statement from the agree pile ends up in a disagree pile. However, having a scale from "least like how I think" and "most like how I think" eliminates this problem.

**Comment by munterkalmsteiner** [comment]
I think the suggested solution could work. @rbritto82 what do you say?

**Comment by rbritto82** [comment]
@munterkalmsteiner and @DeepikaBadampudi, I like the solution. I got another feedback late yesterday and I'll add the issues here. I can say the person had the same concern showed in this issue.

**Comment by munterkalmsteiner** [comment]
See 8626178ba440fc60d15f966f0267dd6b917a363d.
I have reframed the task by removing Agree/Neutral/Disagree from the piles and adding "Most/Least like I think" to the ranking. Updated also the task description.
